[package]
name = "font-kit"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
bitflags = "1.0"
euclid = "0.17"
log = "0.4"
lyon_path = "0.10"
memmap = "0.6"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.2"

# [target.'cfg(target_family = "windows")'.dependencies.dwrote]
# path = "../dwrote-rs"

# [target.'cfg(target_os = "macos")'.dependencies.cocoa]
# path = "/Users/pcwalton/Source/core-foundation-rs/cocoa"

# [target.'cfg(target_os = "macos")'.dependencies.core-foundation]
# path = "/Users/pcwalton/Source/core-foundation-rs/core-foundation"

# [target.'cfg(target_os = "macos")'.dependencies.core-graphics]
# path = "/Users/pcwalton/Source/core-foundation-rs/core-graphics"

# [target.'cfg(target_os = "macos")'.dependencies.core-text]
# path = "/Users/pcwalton/Source/core-foundation-rs/core-text"

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
freetype = "0.3"
